(() => {
  'use strict';
  const KEY='millionTrackerDataV2';
  const DEFAULT={name:'Arthur',goal:1000000,transactions:[]};
  let data=load();
  let selectedPeriod='today';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const money=n=>new Intl.NumberFormat('fr-FR').format(Math.round(Number(n)||0))+' F';
  const today=()=>{const d=new Date();return d.toISOString().slice(0,10)};
  const dateText=v=>new Date(v+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'});
  function load(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...DEFAULT}}}
  function save(){localStorage.setItem(KEY,JSON.stringify(data))}
  function totals(){let income=0,expense=0,saving=0,trading=0;data.transactions.forEach(t=>{if(t.type==='income')income+=t.amount;if(t.type==='expense')expense+=t.amount;if(t.type==='saving')saving+=t.amount;if(t.type==='trading')trading+=t.amount});return{income,expense,saving,trading,balance:income-expense-saving,goal:Math.min(saving,data.goal)}}
  function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
  function render(){const t=totals(),pct=Math.min(100,t.goal/data.goal*100||0);setText('userName',data.name);setText('topName',data.name);setText('avatar',(data.name||'A').charAt(0).toUpperCase());setText('currentDate',new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}));setText('incomeTotal',money(t.income));setText('expenseTotal',money(t.expense));setText('savingTotal',money(t.saving));setText('balanceTotal',money(t.balance));setText('goalAmount',money(t.goal));setText('goalPercent',pct.toFixed(1)+' %');setText('goalRemaining',money(Math.max(0,data.goal-t.goal))+' restant');setText('sidePercent',pct.toFixed(1)+' %');setText('goalPageAmount',money(t.goal));setText('goalPagePercent',pct.toFixed(1)+' %');setText('savingPageTotal',money(t.saving));setText('tradingTotal',money(t.trading));setText('tradingStat',money(t.trading));setText('operationCount',data.transactions.length);setText('settingsName',data.name);setText('settingsGoal',data.goal);['goalProgress','goalPageProgress','sideProgress'].forEach(id=>{const e=document.getElementById(id);if(e)e.style.width=pct+'%'});score(t);stats(t);history();watch(t);chart();setTodayFields()}
  function score(t){if(!data.transactions.length){setText('score','—');setText('scoreText','Aucune donnée suffisante');['scoreSaving','scoreExpense','scoreBusiness','scoreTrading'].forEach(id=>setText(id,'—'));return}let savingRate=t.income?t.saving/t.income*100:0,expenseRate=t.income?t.expense/t.income*100:0,sc=Math.max(0,Math.min(100,Math.round(savingRate*.7+(100-Math.min(100,expenseRate))*.3)));setText('score',sc);setText('scoreText',sc>=70?'Bonne discipline financière':sc>=40?'À améliorer':'À surveiller');setText('scoreSaving',Math.round(savingRate)+'%');setText('scoreExpense',Math.round(expenseRate)+'%');setText('scoreBusiness',money(data.transactions.filter(x=>x.type==='income'&&x.category==='Business').reduce((a,x)=>a+x.amount,0)));setText('scoreTrading',money(t.trading))}
  function stats(t){setText('savingRate',t.income?(t.saving/t.income*100).toFixed(1)+'%':'—');setText('expenseRate',t.income?(t.expense/t.income*100).toFixed(1)+'%':'—')}
  function history(){const box=$('#historyList');if(!box)return;if(!data.transactions.length){box.innerHTML='<div class="empty">Historique vide<small>Tes opérations apparaîtront ici.</small></div>';return}box.innerHTML=[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date)).map(t=>`<div class="history-item"><span class="history-type ${t.type}">${label(t.type)}</span><div><strong>${escapeHtml(t.title)}</strong><small>${dateText(t.date)}${t.note?' · '+escapeHtml(t.note):''}</small></div><small>${escapeHtml(t.category||'')}</small><strong>${t.type==='expense'||t.type==='trading'&&t.amount<0?'-':''}${money(Math.abs(t.amount))}</strong></div>`).join('')}
  const label=t=>({income:'ENTRÉE',expense:'DÉPENSE',saving:'ÉPARGNE',trading:'TRADING'}[t]||t.toUpperCase());
  function watch(t){const box=$('#watch');let a=[];if(t.income&&t.expense>t.income)a.push(['danger','Dépenses supérieures aux revenus','Tes dépenses dépassent actuellement tes revenus.']);if(t.income&&t.saving===0)a.push(['','Épargne à renforcer','Aucune épargne n’est encore enregistrée.']);if(!a.length){box.innerHTML='<div class="empty">Aucune alerte<small>Les alertes apparaîtront lorsque suffisamment de données seront disponibles.</small></div>';return}box.innerHTML=a.map(x=>`<div class="watch-item ${x[0]}"><div><b>${x[1]}</b><p>${x[2]}</p></div></div>`).join('')}
  function periodStart(period){const d=new Date();if(period==='today')return today();if(period==='7')d.setDate(d.getDate()-6);if(period==='30')d.setDate(d.getDate()-29);if(period==='3m')d.setMonth(d.getMonth()-3);if(period==='6m')d.setMonth(d.getMonth()-6);if(period==='1y')d.setFullYear(d.getFullYear()-1);return d.toISOString().slice(0,10)}
  function chart(){const box=$('#chart');if(!box)return;const start=periodStart(selectedPeriod);const filtered=data.transactions.filter(t=>t.date>=start&&t.date<=today());if(!filtered.length){box.innerHTML='<div class="chart-empty">Aucune donnée disponible<small>Aucune opération pour cette période.</small></div>';return}const max=Math.max(...filtered.map(t=>Math.abs(t.amount)),1);box.innerHTML='<div class="chart-bars">'+filtered.map(t=>`<i title="${label(t.type)} · ${money(t.amount)} · ${dateText(t.date)}" style="height:${Math.max(8,Math.min(95,Math.abs(t.amount)/max*85))}%" class="${t.type}"></i>`).join('')+'</div>'}
  function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function setTodayFields(){['incomeDate','expenseDate','savingDate','tradingDate'].forEach(id=>{const e=document.getElementById(id);if(e&&!e.value)e.value=today()});const a=$('#incomeAmount'),p=$('#incomePreview');if(a&&p)p.textContent=money((Number(a.value)||0)*.3)}
  function add(type,amount,title,category,date,note){data.transactions.push({id:Date.now()+Math.random(),type,amount:Number(amount),title,category,date,note});save();render();location.hash='dashboard';show('dashboard');alert('Opération enregistrée.')}
  function bindForms(){const inf=$('#incomeForm');inf?.addEventListener('submit',e=>{e.preventDefault();add('income',$('#incomeAmount').value,$('#incomeSource').value,$('#incomeCategory').value,$('#incomeDate').value,$('#incomeNote').value);e.target.reset();setTodayFields()});$('#incomeAmount')?.addEventListener('input',e=>setText('incomePreview',money(Number(e.target.value)*.3)));const exf=$('#expenseForm');exf?.addEventListener('submit',e=>{e.preventDefault();add('expense',$('#expenseAmount').value,$('#expenseSource').value,$('#expenseCategory').value,$('#expenseDate').value,$('#expenseNote').value);e.target.reset();setTodayFields()});$('#savingForm')?.addEventListener('submit',e=>{e.preventDefault();add('saving',$('#savingAmount').value,'Épargne','Épargne',$('#savingDate').value,$('#savingNote').value);e.target.reset();setTodayFields()});$('#tradingForm')?.addEventListener('submit',e=>{e.preventDefault();add('trading',$('#tradingAmount').value,'Résultat trading','Trading',$('#tradingDate').value,$('#tradingNote').value);e.target.reset();setTodayFields()});$('#settingsForm')?.addEventListener('submit',e=>{e.preventDefault();data.name=$('#settingsName').value.trim()||'Arthur';data.goal=Math.max(1,Number($('#settingsGoal').value)||1000000);save();render();alert('Paramètres enregistrés.')});$('#clearHistory')?.addEventListener('click',()=>{if(confirm('Supprimer toutes les données enregistrées ?')){data.transactions=[];save();render()}})}
  function show(view){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.section===view));$$('.nav-item').forEach(a=>a.classList.toggle('active',a.dataset.view===view));$('#sidebar')?.classList.remove('open')}
  function bindNav(){$$('.nav-item').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const v=a.dataset.view;location.hash=v;show(v)}));window.addEventListener('hashchange',()=>show(location.hash.replace('#','')||'dashboard'));$('#mobileMenu')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$$('.period').forEach(b=>b.addEventListener('click',()=>{selectedPeriod=b.dataset.period||'today';$$('.period').forEach(x=>x.classList.remove('active'));b.classList.add('active');chart()}))}
  document.addEventListener('DOMContentLoaded',()=>{bindNav();bindForms();render();show(location.hash.replace('#','')||'dashboard')});
})();
